/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthManageresourcesImport } from './routes/_auth/manage_resources'
import { Route as AuthManagereportImport } from './routes/_auth/manage_report'
import { Route as AuthChatImport } from './routes/_auth/chat'
import { Route as AuthAddresourcesImport } from './routes/_auth/add_resources'
import { Route as AuthAddreportImport } from './routes/_auth/add_report'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthIndexRoute = AuthIndexImport.update({
  id: '/_auth/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthManageresourcesRoute = AuthManageresourcesImport.update({
  id: '/_auth/manage_resources',
  path: '/manage_resources',
  getParentRoute: () => rootRoute,
} as any)

const AuthManagereportRoute = AuthManagereportImport.update({
  id: '/_auth/manage_report',
  path: '/manage_report',
  getParentRoute: () => rootRoute,
} as any)

const AuthChatRoute = AuthChatImport.update({
  id: '/_auth/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const AuthAddresourcesRoute = AuthAddresourcesImport.update({
  id: '/_auth/add_resources',
  path: '/add_resources',
  getParentRoute: () => rootRoute,
} as any)

const AuthAddreportRoute = AuthAddreportImport.update({
  id: '/_auth/add_report',
  path: '/add_report',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/add_report': {
      id: '/_auth/add_report'
      path: '/add_report'
      fullPath: '/add_report'
      preLoaderRoute: typeof AuthAddreportImport
      parentRoute: typeof rootRoute
    }
    '/_auth/add_resources': {
      id: '/_auth/add_resources'
      path: '/add_resources'
      fullPath: '/add_resources'
      preLoaderRoute: typeof AuthAddresourcesImport
      parentRoute: typeof rootRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatImport
      parentRoute: typeof rootRoute
    }
    '/_auth/manage_report': {
      id: '/_auth/manage_report'
      path: '/manage_report'
      fullPath: '/manage_report'
      preLoaderRoute: typeof AuthManagereportImport
      parentRoute: typeof rootRoute
    }
    '/_auth/manage_resources': {
      id: '/_auth/manage_resources'
      path: '/manage_resources'
      fullPath: '/manage_resources'
      preLoaderRoute: typeof AuthManageresourcesImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutLazyRoute
  '/add_report': typeof AuthAddreportRoute
  '/add_resources': typeof AuthAddresourcesRoute
  '/chat': typeof AuthChatRoute
  '/manage_report': typeof AuthManagereportRoute
  '/manage_resources': typeof AuthManageresourcesRoute
  '/': typeof AuthIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/add_report': typeof AuthAddreportRoute
  '/add_resources': typeof AuthAddresourcesRoute
  '/chat': typeof AuthChatRoute
  '/manage_report': typeof AuthManagereportRoute
  '/manage_resources': typeof AuthManageresourcesRoute
  '/': typeof AuthIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutLazyRoute
  '/_auth/add_report': typeof AuthAddreportRoute
  '/_auth/add_resources': typeof AuthAddresourcesRoute
  '/_auth/chat': typeof AuthChatRoute
  '/_auth/manage_report': typeof AuthManagereportRoute
  '/_auth/manage_resources': typeof AuthManageresourcesRoute
  '/_auth/': typeof AuthIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/add_report'
    | '/add_resources'
    | '/chat'
    | '/manage_report'
    | '/manage_resources'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/add_report'
    | '/add_resources'
    | '/chat'
    | '/manage_report'
    | '/manage_resources'
    | '/'
  id:
    | '__root__'
    | '/about'
    | '/_auth/add_report'
    | '/_auth/add_resources'
    | '/_auth/chat'
    | '/_auth/manage_report'
    | '/_auth/manage_resources'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutLazyRoute: typeof AboutLazyRoute
  AuthAddreportRoute: typeof AuthAddreportRoute
  AuthAddresourcesRoute: typeof AuthAddresourcesRoute
  AuthChatRoute: typeof AuthChatRoute
  AuthManagereportRoute: typeof AuthManagereportRoute
  AuthManageresourcesRoute: typeof AuthManageresourcesRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutLazyRoute: AboutLazyRoute,
  AuthAddreportRoute: AuthAddreportRoute,
  AuthAddresourcesRoute: AuthAddresourcesRoute,
  AuthChatRoute: AuthChatRoute,
  AuthManagereportRoute: AuthManagereportRoute,
  AuthManageresourcesRoute: AuthManageresourcesRoute,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/_auth/add_report",
        "/_auth/add_resources",
        "/_auth/chat",
        "/_auth/manage_report",
        "/_auth/manage_resources",
        "/_auth/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_auth/add_report": {
      "filePath": "_auth/add_report.tsx"
    },
    "/_auth/add_resources": {
      "filePath": "_auth/add_resources.tsx"
    },
    "/_auth/chat": {
      "filePath": "_auth/chat.tsx"
    },
    "/_auth/manage_report": {
      "filePath": "_auth/manage_report.tsx"
    },
    "/_auth/manage_resources": {
      "filePath": "_auth/manage_resources.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
